/**
 * Factory functions for test data.
 */
import type { Lead, QueueItem } from '../../types'

export function makeLead(overrides: Partial<Lead> = {}): Lead {
  return {
    id: crypto.randomUUID(),
    name: 'Test Business',
    category: 'restaurant',
    address: '123 Test St, London',
    city: 'London',
    phone: '+447700900000',
    email: 'test@business.com',
    google_place_id: 'ChIJ_test',
    google_rating: 4.5,
    google_review_count: 25,
    website_detected: null,
    status: 'discovered',
    status_updated_at: new Date().toISOString(),
    site_html: null,
    site_prompt: null,
    vercel_project_id: null,
    vercel_deployment_url: 'https://test-business.vercel.app',
    final_domain: null,
    email_sent_at: null,
    email_opened_at: null,
    email_clicked_at: null,
    bland_call_id: null,
    call_initiated_at: null,
    call_completed_at: null,
    call_outcome: null,
    demo_booked_at: null,
    calendly_event_url: null,
    pipeline_run_id: null,
    error: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    viability_score: null,
    viability_notes: null,
    companies_house_status: null,
    companies_house_number: null,
    contact_name: null,
    closing_call_id: null,
    closing_call_at: null,
    closing_summary: null,
    desired_domain: null,
    needs_domain: null,
    needs_email_setup: null,
    cta_type: null,
    cta_value: null,
    requested_changes: null,
    stripe_payment_link: null,
    paid_at: null,
    total_price: null,
    creative_brief: null,
    review_attempts: null,
    review_result: null,
    skip_to_deploy: null,
    followup_call_id: null,
    ...overrides,
  }
}

export function makeQueueItem(overrides: Partial<QueueItem> = {}): QueueItem {
  return {
    id: crypto.randomUUID(),
    lead_id: crypto.randomUUID(),
    pipeline_run_id: null,
    queue_name: 'verify',
    priority: 0,
    scheduled_at: null,
    status: 'pending',
    attempts: 0,
    error: null,
    metadata: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...overrides,
  }
}
